apiVersion: v1
kind: PersistentVolume
metadata:
  name: static-pv
spec:
  storageClassName: sitio
  capacity:
    storage: 1Gi
  accessModes:
    - ReadOnlyMany
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: /mnt/web

