apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: static-pvc
spec:
  storageClassName: sitio
  volumeName: static-pv
  accessModes:
    - ReadOnlyMany
  resources:
    requests:
      storage: 1Gi

